#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_RMI4_I2C)	+= synaptics_dsx_rmi4_i2c.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_RMI_DEV)	+= rmi_dev.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_RMI4_F54)	+= rmi_f54.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_RMI4_FW_UPDATE) += synaptics_dsx_s3202_fw_update.o rmi_fw_update.o
