obj-$(CONFIG_EXTERNAL_MISC_DRIVERS)	+= drivers/
obj-$(CONFIG_EXTERNAL_INTEL_MEDIA)	+= intel_media/
obj-$(CONFIG_DEBUG_TOOLS)               += drivers/external_drivers/debug_tools/powerdk/src
obj-$(CONFIG_DEBUG_TOOLS)               += drivers/external_drivers/debug_tools/socwatchdk/src
obj-$(CONFIG_DEBUG_TOOLS)               += drivers/external_drivers/debug_tools/vtunedk/src
